TOPDIR = ../../..

SUBDIRS =

CSRCS =

CXXSRCS = \
	spi.cpp
	
INCDIRS = \
$(TOPDIR)/Dozer/Main/Header \
$(TOPDIR)/Dozer/Main/Header/Global \
$(TOPDIR)/Dozer/Main/Header/System \
$(TOPDIR)/Dozer/Main/Header/BLE \
../../Lib \
../../Lib/CRC \
../../Lib/cJSON \
../../CMSIS \
../../STM32F4xx_HAL_Driver/Inc \
../EFlash \
../SIM5320 \
../../Device/Flash \
../../FreeRTOS/v10.1.1/include \
../../FreeRTOS/v10.1.1/portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk