TOPDIR = ../../../..

SUBDIRS =

CSRCS =

CXXSRCS = \
	Flash.cpp \
	LED.cpp \
	WDG.cpp \
	Buttons.cpp
	
INCDIRS = \
../../Header \
../../Header/Global \
../../Header/System \
$(TOPDIR)/Common/Lib \
$(TOPDIR)/Common/Lib/CRC \
$(TOPDIR)/Common/CMSIS \
$(TOPDIR)/Common/STM32F4xx_HAL_Driver/Inc \
$(TOPDIR)/Common/Periphery/EFlash \
$(TOPDIR)/Common/Periphery/Motors \
$(TOPDIR)/Common/Device/Flash \
$(TOPDIR)/Common/FreeRTOS/V9.0.0/Header \
$(TOPDIR)/Common/FreeRTOS/V9.0.0/Portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk