TOPDIR = ../../../..

SUBDIRS = \
	MemMang
	
CSRCS = \
	croutine.c \
	list.c \
	queue.c \
	tasks.c \
	timers.c
	
CXXSRCS =

INCDIRS = ../Header $(TOPDIR)/Dozer/Main/Header/System ../Portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk