TOPDIR = ../../..

SUBDIRS =

CSRCS = \
	stm32f4xx_ll_gpio.c \
	stm32f4xx_ll_rcc.c
#	stm32f4xx_ll_usart.c \
#	stm32f4xx_ll_dma.c
	
CXXSRCS =

ASRCS =

INCDIRS = \
../Inc \
../../CMSIS

include $(TOPDIR)/common.mk