TOPDIR = ../../..

SUBDIRS =

CSRCS = \
	stm32f4xx_ll_gpio.c \
	stm32f4xx_ll_tim.c
#	stm32f4xx_hal_msp.c \
	
CXXSRCS =

ASRCS =

INCDIRS = \
../Inc \
../../CMSIS

include $(TOPDIR)/common.mk