TOPDIR = ../..

SUBDIRS =

CSRCS = \
	Syscalls.c
	
CXXSRCS = \
	Clocks.cpp \
	FreeRTOS_Tools.cpp

INCDIRS = \
$(TOPDIR)/Dozer/Main/Header \
$(TOPDIR)/Dozer/Main/Header/Global \
$(TOPDIR)/Dozer/Main/Header/System \
../Lib \
../Lib/CRC \
../CMSIS \
../CMSIS/Lib \
../Periphery/EFlash \
../Device/Flash \
../FreeRTOS/V9.0.0/Header \
../FreeRTOS/V9.0.0/Portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk