TOPDIR = ../..

SUBDIRS =

CSRCS = \
	Syscalls.c
	
CXXSRCS = \
	Clocks.cpp \
	FreeRTOS_Tools.cpp

INCDIRS = \
$(TOPDIR)/Dozer/Main/Header \
$(TOPDIR)/Dozer/Main/Header/Global \
$(TOPDIR)/Dozer/Main/Header/System \
../Lib \
../Lib/CRC \
../Lib/cJSON \
../CMSIS \
../STM32F4xx_HAL_Driver/Inc \
../Periphery/EFlash \
../Periphery/Motors \
../Periphery/SIM5320 \
../Device/Flash \
../FreeRTOS/v10.1.1/include \
../FreeRTOS/v10.1.1/portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk