TOPDIR = ../../..

SUBDIRS =

CSRCS =

CXXSRCS = \
	Settings.cpp

INCDIRS = .. \
../CRC \
../cJSON \
$(TOPDIR)/Dozer/Main/Header \
$(TOPDIR)/Dozer/Main/Header/Global \
$(TOPDIR)/Dozer/Main/Header/BLE \
$(TOPDIR)/Dozer/Main/Header/System \
../../CMSIS \
../../STM32F4xx_HAL_Driver/Inc \
../../Periphery/EFlash \
../../Periphery/Motors \
../../Periphery/SIM5320 \
../../Device/Flash \
../../FreeRTOS/v10.1.1/include \
../../FreeRTOS/v10.1.1/portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk