// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_web_server                      12
#define gattdb_ip_on                           14
#define gattdb_date_time                       17
#define gattdb_dozer_number                    21
#define gattdb_pool_number                     23
#define gattdb_dozer_name                      25
#define gattdb_schedule_1_1                    27
#define gattdb_schedule_1_2                    29
#define gattdb_schedule_1_3                    31
#define gattdb_schedule_1_4                    33
#define gattdb_schedule_1_5                    35
#define gattdb_schedule_1_6                    37
#define gattdb_schedule_1_7                    39
#define gattdb_schedule_1_8                    41
#define gattdb_schedule_1_9                    43
#define gattdb_schedule_1_10                   45
#define gattdb_schedule_1_11                   47
#define gattdb_schedule_1_12                   49
#define gattdb_schedule_1_13                   51
#define gattdb_schedule_1_14                   53
#define gattdb_schedule_1_15                   55
#define gattdb_schedule_1_16                   57
#define gattdb_schedule_1_17                   59
#define gattdb_schedule_1_18                   61
#define gattdb_schedule_1_19                   63
#define gattdb_schedule_1_20                   65
#define gattdb_schedule_1_21                   67
#define gattdb_schedule_1_22                   69
#define gattdb_schedule_1_23                   71
#define gattdb_schedule_1_24                   73
#define gattdb_schedule_2                      75
#define gattdb_feed_size                       77
#define gattdb_feeding_freq                    79
#define gattdb_feeding_ratio                   81
#define gattdb_pool_volume                     83
#define gattdb_user_text                       85
#define gattdb_fish_weight                     88
#define gattdb_age                             90
#define gattdb_quantity                        92
#define gattdb_loss                            94
#define gattdb_sold                            96
#define gattdb_change                          98
#define gattdb_type                           101
#define gattdb_quantity_2                     103
#define gattdb_biomass                        106
#define gattdb_growth_rate                    109
#define gattdb_density                        112
#define gattdb_doze                           115
#define gattdb_statistics_weight              118
#define gattdb_calibrate                      122
#define gattdb_feed_weight                    124
#define gattdb_gate                           127
#define gattdb_max_weight                     130
#define gattdb_op_time                        132
#define gattdb_temperature                    135
#define gattdb_dispancer                      138
#define gattdb_alarm_empty                    140
#define gattdb_alarm_overheat                 143
#define gattdb_warning_few_feed               146
#define gattdb_alarm_motor_error              149
#define gattdb_current_doze                   152

#endif
