// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_web_server                      12
#define gattdb_ip_on                           14
#define gattdb_date_time                       17
#define gattdb_number_of_digitals              19
#define gattdb_dozer_number                    22
#define gattdb_pool_number                     24
#define gattdb_dozer_name                      26
#define gattdb_schedule_1_1                    28
#define gattdb_schedule_1_2                    30
#define gattdb_schedule_1_3                    32
#define gattdb_schedule_1_4                    34
#define gattdb_schedule_1_5                    36
#define gattdb_schedule_1_6                    38
#define gattdb_schedule_1_7                    40
#define gattdb_schedule_1_8                    42
#define gattdb_schedule_1_9                    44
#define gattdb_schedule_1_10                   46
#define gattdb_schedule_1_11                   48
#define gattdb_schedule_1_12                   50
#define gattdb_schedule_1_13                   52
#define gattdb_schedule_1_14                   54
#define gattdb_schedule_1_15                   56
#define gattdb_schedule_1_16                   58
#define gattdb_schedule_1_17                   60
#define gattdb_schedule_1_18                   62
#define gattdb_schedule_1_19                   64
#define gattdb_schedule_1_20                   66
#define gattdb_schedule_1_21                   68
#define gattdb_schedule_1_22                   70
#define gattdb_schedule_1_23                   72
#define gattdb_schedule_1_24                   74
#define gattdb_schedule_2                      76
#define gattdb_feed_size                       78
#define gattdb_feeding_freq                    80
#define gattdb_feeding_ratio                   82
#define gattdb_pool_volume                     84
#define gattdb_user_text                       86
#define gattdb_fish_weight                     89
#define gattdb_age                             91
#define gattdb_quantity                        93
#define gattdb_loss                            95
#define gattdb_sold                            97
#define gattdb_change                          99
#define gattdb_type                           102
#define gattdb_quantity_2                     104
#define gattdb_biomass                        107
#define gattdb_growth_rate                    110
#define gattdb_density                        113
#define gattdb_doze                           116
#define gattdb_statistics_weight              119
#define gattdb_calibrate                      123
#define gattdb_feed_weight                    125
#define gattdb_gate                           128
#define gattdb_max_weight                     131
#define gattdb_op_time                        133
#define gattdb_temperature                    136
#define gattdb_dispancer                      139
#define gattdb_alarm_empty                    141
#define gattdb_alarm_overheat                 144
#define gattdb_warning_few_feed               147
#define gattdb_alarm_motor_error              150
#define gattdb_current_doze                   153

#endif
