// Copyright 2019 Silicon Laboratories, Inc.
//
//

/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "bg_gattdb_def.h"

extern const struct bg_gattdb_def bg_gattdb_data;

#define gattdb_service_changed_char             3
#define gattdb_device_name                      7
#define gattdb_web_server                      12
#define gattdb_ip_on                           14
#define gattdb_inn                             16
#define gattdb_psw                             18
#define gattdb_date_time                       21
#define gattdb_dozer_number                    25
#define gattdb_pool_number                     27
#define gattdb_dozer_name                      29
#define gattdb_feed_size                       31
#define gattdb_feeding_freq                    33
#define gattdb_feeding_ratio                   35
#define gattdb_pool_volume                     37
#define gattdb_user_text                       39
#define gattdb_fish_weight                     42
#define gattdb_age                             44
#define gattdb_quantity                        46
#define gattdb_loss                            48
#define gattdb_sold                            50
#define gattdb_change                          52
#define gattdb_type                            55
#define gattdb_quantity_2                      57
#define gattdb_biomass                         60
#define gattdb_growth_rate                     63
#define gattdb_density                         66
#define gattdb_doze                            69
#define gattdb_statistics_weight               72
#define gattdb_calibrate                       76
#define gattdb_feed_weight                     78
#define gattdb_gate                            81
#define gattdb_max_weight                      84
#define gattdb_op_time                         86
#define gattdb_temperature                     89
#define gattdb_dispancer                       92
#define gattdb_alarm_empty                     94
#define gattdb_alarm_overheat                  97
#define gattdb_warning_few_feed               100
#define gattdb_alarm_motor_error              103
#define gattdb_current_doze                   106

#endif
