TOPDIR = ../../../..

SUBDIRS =

CSRCS =

CXXSRCS = \
	Init.cpp \
	Interrupts.cpp
	
INCDIRS = \
../../Header \
../../Header/Global \
../../Header/System \
$(TOPDIR)/Common/Lib \
$(TOPDIR)/Common/Lib/CRC \
$(TOPDIR)/Common/Lib/cJSON \
$(TOPDIR)/Common/CMSIS \
$(TOPDIR)/Common/STM32F4xx_HAL_Driver/Inc \
$(TOPDIR)/Common/Periphery/EFlash \
$(TOPDIR)/Common/Periphery/Motors \
$(TOPDIR)/Common/Device/Flash \
$(TOPDIR)/Common/FreeRTOS/v10.1.1/include \
$(TOPDIR)/Common/FreeRTOS/v10.1.1/portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk