TOPDIR = ../../..

SUBDIRS =

CSRCS =

CXXSRCS = CRC.cpp

INCDIRS = . \
.. \
$(TOPDIR)/Dozer/Main/Header \
$(TOPDIR)/Dozer/Main/Header/Global \
$(TOPDIR)/Dozer/Main/Header/System \
../../CMSIS \
../../STM32F4xx_HAL_Driver/Inc \
../../Periphery/EFlash \
../../Periphery/Motors \
../../Device/Flash \
../../FreeRTOS/V9.0.0/Header \
../../FreeRTOS/V9.0.0/Portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk