TOPDIR = ../../..

SUBDIRS = \
	portable/MemMang \
	portable/GCC/ARM_CM4F
	
CSRCS = \
	croutine.c \
	list.c \
	queue.c \
	tasks.c \
	timers.c \
	stream_buffer.c
	
CXXSRCS =

INCDIRS = ./include $(TOPDIR)/Dozer/Main/Header/System ./portable/GCC/ARM_CM4F

include $(TOPDIR)/common.mk